% 
% 使用去除了所有工具标签的ImageNet2012（LSVRC2012，共925分类）训练的alexnet
% 训练参数：
% batch size = 128, momentum = 0.9, weight decay = 0.0005, training epoch = 90, 
% learning rate = 0.01, learning rate decay = 10 times for every 30 epochs.
% 

clear;clc;close all;

batchsize = 128;
momentum = 0.9;
weightdecay = 0.0005;
epoch = 90;
learningrate = 0.01;

%% 鍔犺浇鏁版嵁闆?
imdsTrain = imageDatastore('train', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imdsValidation = imageDatastore('val', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

%% 鍔犺浇缃戠粶
numClasses = 925;

net = imagePretrainedNetwork("alexnet","weights","none","NumClasses",numClasses);

inputSize = net.Layers(1).InputSize;

%% 璁粌
pixelRange = [-30 30];
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange);
augimdsTrain = augmentedImageDatastore(inputSize(1:2),imdsTrain, ...
    'DataAugmentation',imageAugmenter);

augimdsValidation = augmentedImageDatastore(inputSize(1:2),imdsValidation);

options = trainingOptions("sgdm", ...
    'ExecutionEnvironment', 'gpu', ...
    'MiniBatchSize', 128, ...
    'MaxEpochs', 90, ...
    'Momentum', momentum, ...
    'L2Regularization', weightdecay, ...
    'InitialLearnRate', learningrate, ...
    'LearnRateDropFactor', 0.1, ...
    'LearnRateDropPeriod', 30, ...
    'Verbose', true, ...   
    'VerboseFrequency', 1, ...
    'ValidationData', augimdsValidation, ...
    'ValidationFrequency', 1, ...
    'Plots', "training-progress");

net = trainnet(augimdsTrain,net,"crossentropy",options);
save('AlexNet_toolincluded.mat', 'net');
